### ISSUE TITLE
Issue with catkin_make

### ISSUE THREAD

**Issue by pjj5049** [ethz-asl/vicon_bridge#10]
Hi,
I'm having an issue getting the repo to completely catkin_make on a Jetson Tk1 board. When we try to make from the parent directory, we receive the error: 

[ 34%] Building CXX object vicon_bridge/CMakeFiles/testclient.dir/src/ViconDataStreamSDK_CPPTest.cpp.o
Linking CXX executable /home/ubuntu/catkin_ws/devel/lib/vicon_bridge/testclient
/usr/bin/ld: skipping incompatible /home/ubuntu/catkin_ws/src/vicon_bridge/vicon_sdk/Vicon_SDK_1.3_Linux/32-bit/libViconDataStreamSDK_CPP.so when searching for -lViconDataStreamSDK_CPP
/usr/bin/ld: cannot find -lViconDataStreamSDK_CPP
collect2: error: ld returned 1 exit status

Any advice on how to proceed would be appreciated.

Thank you!

**Comment by kdhansen** [comment]
vicon_bridge depends on the SDK provided by Vicon (`libViconDataStreamSDK_CPP.so`). This come precompiled from Vicon for Windows and Linux on x86 and x64. The Jetson TK1 is basen on ARM processors and CUDA cores, this is probably not compatible with the given libraries.

There has been [talk about swiching to VRPN](https://github.com/ethz-asl/vicon_bridge/issues/8), but I don't know about it.

I have seen [an other ROS package](https://github.com/cburbridge/uuisrc-ros-pkg/tree/master/vicon)  that implements the protocol instead of using the precompiled library, I have not tried it, but that may work for you.

**Comment by markusachtelik** [comment]
thanks for answering! I think we can close this.
