### ISSUE TITLE
empty character cannot be handled

### ISSUE THREAD

**Issue by akrv** [ethz-asl/vicon_bridge#18]
When vicon bridge is installed and the lauch file is started with correct host:port combo.
it starts but since one of the rigid body is "Paket2 ", the node crashes. 

**`[ INFO] [1513782445.900415816]: creating new object Paket2 /Paket2 ...
terminate called after throwing an instance of 'ros::InvalidNameException'
  what():  Character [ ] at element [12] is not valid in Graph Resource Name [vicon/Paket2 /Paket2].  Valid characters are a-z, A-Z, 0-9, / and _.`**

**Comment by helenol** [comment]
Don't use spaces in your rigid body names?

**Comment by akrv** [comment]
- The name in tracker doesn't have space char.
- Handling space char is a limitation in [ROS names](http://wiki.ros.org/Names)
- I tried a quick workaround 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (since there are multiple experiments and Paket2 is not part of our experiment):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; remove the space but doesn't seem to work when the "const" is removed.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `void createSegmentThread(const string subject_name, const string segment_name)`

is there a config to accept/ignore certain expressions to be loaded from the datastream API?
(anything Paket, only rb1_base etc?)

**Comment by helenol** [comment]
Hahaha sorry, I feel like a jerk now; didn't get that it was a character being added from your original issue. 
Weird that it's getting added, since we've never seen this issue before but yes there's no workaround other than ignore it or strip the character out.

As an aside, we have mostly transitioned to using the vrpn client in our lab: https://github.com/ethz-asl/ros_vrpn_client
Which is more maintained/will hopefully have fewer issues.
